# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rectbot_cv/KeyPoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class KeyPoint(genpy.Message):
  _md5sum = "1cd825e8df87066e1486d6a8d6cfd264"
  _type = "rectbot_cv/KeyPoint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Float32 x
std_msgs/Float32 y
std_msgs/Float32 score
================================================================================
MSG: std_msgs/Float32
float32 data"""
  __slots__ = ['x','y','score']
  _slot_types = ['std_msgs/Float32','std_msgs/Float32','std_msgs/Float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,score

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(KeyPoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = std_msgs.msg.Float32()
      if self.y is None:
        self.y = std_msgs.msg.Float32()
      if self.score is None:
        self.score = std_msgs.msg.Float32()
    else:
      self.x = std_msgs.msg.Float32()
      self.y = std_msgs.msg.Float32()
      self.score = std_msgs.msg.Float32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3f().pack(_x.x.data, _x.y.data, _x.score.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.x is None:
        self.x = std_msgs.msg.Float32()
      if self.y is None:
        self.y = std_msgs.msg.Float32()
      if self.score is None:
        self.score = std_msgs.msg.Float32()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.x.data, _x.y.data, _x.score.data,) = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3f().pack(_x.x.data, _x.y.data, _x.score.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.x is None:
        self.x = std_msgs.msg.Float32()
      if self.y is None:
        self.y = std_msgs.msg.Float32()
      if self.score is None:
        self.score = std_msgs.msg.Float32()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.x.data, _x.y.data, _x.score.data,) = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
