// Generated by gencpp from file rectbot_cv/KeyPoint.msg
// DO NOT EDIT!


#ifndef RECTBOT_CV_MESSAGE_KEYPOINT_H
#define RECTBOT_CV_MESSAGE_KEYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>

namespace rectbot_cv
{
template <class ContainerAllocator>
struct KeyPoint_
{
  typedef KeyPoint_<ContainerAllocator> Type;

  KeyPoint_()
    : x()
    , y()
    , score()  {
    }
  KeyPoint_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , score(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _x_type;
  _x_type x;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _y_type;
  _y_type y;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _score_type;
  _score_type score;





  typedef boost::shared_ptr< ::rectbot_cv::KeyPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rectbot_cv::KeyPoint_<ContainerAllocator> const> ConstPtr;

}; // struct KeyPoint_

typedef ::rectbot_cv::KeyPoint_<std::allocator<void> > KeyPoint;

typedef boost::shared_ptr< ::rectbot_cv::KeyPoint > KeyPointPtr;
typedef boost::shared_ptr< ::rectbot_cv::KeyPoint const> KeyPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rectbot_cv::KeyPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rectbot_cv::KeyPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rectbot_cv::KeyPoint_<ContainerAllocator1> & lhs, const ::rectbot_cv::KeyPoint_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.score == rhs.score;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rectbot_cv::KeyPoint_<ContainerAllocator1> & lhs, const ::rectbot_cv::KeyPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rectbot_cv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rectbot_cv::KeyPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rectbot_cv::KeyPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rectbot_cv::KeyPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rectbot_cv::KeyPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rectbot_cv::KeyPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rectbot_cv::KeyPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rectbot_cv::KeyPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1cd825e8df87066e1486d6a8d6cfd264";
  }

  static const char* value(const ::rectbot_cv::KeyPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1cd825e8df87066eULL;
  static const uint64_t static_value2 = 0x1486d6a8d6cfd264ULL;
};

template<class ContainerAllocator>
struct DataType< ::rectbot_cv::KeyPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rectbot_cv/KeyPoint";
  }

  static const char* value(const ::rectbot_cv::KeyPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rectbot_cv::KeyPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32 x\n"
"std_msgs/Float32 y\n"
"std_msgs/Float32 score\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::rectbot_cv::KeyPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rectbot_cv::KeyPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KeyPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rectbot_cv::KeyPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rectbot_cv::KeyPoint_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.y);
    s << indent << "score: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RECTBOT_CV_MESSAGE_KEYPOINT_H
